name: "Build and Push"

inputs:
  REGISTRY_USER:
    required: false
  REGISTRY_PASSWORD:
    required: false

runs:
  using: "composite"
  steps:
  - name: build rpi
    shell: bash
    run: |
      ./build.sh \
        --base quay.io/almalinuxorg/almalinux-bootc-rpi:10 \
        --registry ghcr.io \
        --repo spiffe/bootc \
        --runtime podman \
        --prefix almalinux-10-rpi
  - name: Log in to the Container registry
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
    uses: redhat-actions/podman-login@v1
    with:
      registry: ghcr.io
      username: ${{ inputs.REGISTRY_USER }}
      password: ${{ inputs.REGISTRY_PASSWORD }}
  - name: push
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
    shell: bash
    run: |
      podman push ghcr.io/spiffe/bootc:almalinux-10-rpi-spire-setup
      podman push ghcr.io/spiffe/bootc:almalinux-10-rpi-spire-agent
      podman push ghcr.io/spiffe/bootc:almalinux-10-rpi-spire-ha-agent
      podman push ghcr.io/spiffe/bootc:almalinux-10-rpi-spire-server
      podman push ghcr.io/spiffe/bootc:almalinux-10-rpi-spire-ha-server

