#!/bin/bash

INSTANCE="$1"

if [[ ! -v INSTANCE ]]; then
  echo Instance must be defined
  exit -1
fi

if [ "$INSTANCE" != "a" -a "$INSTANCE" != "b" ]; then
  echo Instance must be either a or b
  exit -1
fi

SELF=a
OTHER=b
if [ "$INSTANCE" != "a" ]; then
  SELF=b
  OTHER=a  
fi

get-tpm-pubhash
if [ $? -eq 1 ]; then
  echo Failed to get tpm pubhash. Please fix before rerunning.
  exit -1
fi

tpm2_readpublic -c 0x81008006 -f pem -o "/etc/spire/server-attestor-tpm/keys/$SELF.pem" > /dev/null 2>&1
if [ $? -ne 0 ]; then
  tpm2_create -G rsa2048:rsassa:null -g sha256 -u key.pub -r key.priv -C 0x81000001
  if [ $? -ne 0 ]; then
    set -e
    tpm2_createprimary -C o -g sha256 -G rsa2048 -c primary.ctx
    tpm2_evictcontrol -C o -c primary.ctx 0x81000001
    tpm2_create -G rsa2048:rsassa:null -g sha256 -u key.pub -r key.priv -C 0x81000001
  fi
fi

if [ ! -f "/etc/spiffe/step-ssh-server/$SELF/values.yaml" ]; then
  setup-spiffe-step-ssh-server "$SELF"
fi

systemctl enable "spiffe-step-ssh-fetchca@$SELF" "spiffe-step-ssh-server@$SELF" "spire-trust-sync@$OTHER"

systemctl mask bootc-fetch-apply-updates.timer

. /etc/spiffe/default-trust-domain.env

hostnamectl --static set-hostname "spire-server-${INSTANCE}.${SPIFFE_TRUST_DOMAIN}"
