#!/bin/bash

ROOT=$(findmnt --target /sysroot -o source -run)
BOOT=$(echo "$ROOT" | sed 's/[0-9]$/1/')

if [ ! -b "$BOOT" ]; then
	echo Could not find boot device
	exit 1
fi

echo Boot device "$BOOT"

mkdir -p /tmp/mnt

set -e
cp -a /usr/share/raspberrypi2-kernel*/*/boot/bcm2712-rpi-5-b.dtb /tmp/dtb.orig
dtmerge /tmp/dtb.orig /tmp/dtb /usr/share/raspberrypi2-kernel*/*/boot/overlays/tpm-slb9670.dtbo spi=on

mount "$BOOT" /tmp/mnt
mv /tmp/mnt/bcm2712-rpi-5-b.dtb /tmp/mnt/bcm2712-rpi-5-b.dtb.old
cp /tmp/dtb /tmp/mnt/bcm2712-rpi-5-b.dtb
umount /tmp/mnt
