name: Build
on:
  pull_request:
    types: [synchronize, opened, reopened]
  release:
    types: [published]

jobs:
  build:
    name: Build images
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: build rpi
      shell: bash
      run: |
        ./build.sh \
          --base quay.io/almalinuxorg/almalinux-bootc-rpi:10 \
          --registry ghcr.io \
          --repo spiffe/bootc \
          --prefix almalinux-10-rpi
