name: Build
on:
  pull_request:
    types: [synchronize, opened, reopened]
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build:
    name: Build images
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Build
      uses: ./.github/actions/action

  build-and-push:
    name: Build images and push
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
      packages: write
    steps:
    - name: Build and Push
      uses: ./.github/actions/action

